package com.zen.smi.exception;

import com.zen.smi.generic.utils.MessageBO;

/**
 * This class contains Employee exception data.
 *
 * @author amantri
 */
public class UserException extends BusinessException {

    /**
     * Autogenerated Id
     */
    public static final long serialVersionUID = -1;

    public UserException(MessageBO messageBO) {
		super(messageBO);
	}


}
