package com.zen.smi.dao.exception;

import com.zen.smi.generic.utils.MessageBO;

/**
 * This class contains GenericDAOException data.
 *
 * @author amantri
 */
public class GenericDAOException extends Exception {

    /**
     * Autogenerated Id
     */
    public static final long serialVersionUID = -1;

    private MessageBO messageBO;
    
    public GenericDAOException(MessageBO messageBO) {
    	this.messageBO = messageBO;
    }
    
    public GenericDAOException(MessageBO messageBO, Throwable e) {
    	super(e);
    	this.messageBO = messageBO;
    }

	public MessageBO getMessageBO() {
		return messageBO;
	}

	public void setMessageBO(MessageBO messageBO) {
		this.messageBO = messageBO;
	}



}
