package com.zen.smi.dao.entities;
// Generated Mar 25, 2018 2:48:28 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fines generated by hbm2java
 */
@Entity
@Table(name = "fines", catalog = "project")
public class Fines implements java.io.Serializable {

	private Integer id;
	private Float fineAmount;
	private String cause;
	private Date payDate;
	private Set<UserFines> userFineses = new HashSet<UserFines>(0);

	public Fines() {
	}

	public Fines(Float fineAmount, String cause, Date payDate, Set<UserFines> userFineses) {
		this.fineAmount = fineAmount;
		this.cause = cause;
		this.payDate = payDate;
		this.userFineses = userFineses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fine_amount", precision = 12, scale = 0)
	public Float getFineAmount() {
		return this.fineAmount;
	}

	public void setFineAmount(Float fineAmount) {
		this.fineAmount = fineAmount;
	}

	@Column(name = "cause", length = 45)
	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pay_date", length = 19)
	public Date getPayDate() {
		return this.payDate;
	}

	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fines")
	public Set<UserFines> getUserFineses() {
		return this.userFineses;
	}

	public void setUserFineses(Set<UserFines> userFineses) {
		this.userFineses = userFineses;
	}

}
