package com.zen.smi.dao.entities;
// Generated Mar 25, 2018 2:48:28 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification")
public class Notification implements java.io.Serializable {

	private Integer id;
	private String ntName;
	private String ntDesc;
	private String ntText;
	private Date createdDate;
	private Date updatedDate;
	private Set<UserNotification> userNotifications = new HashSet<UserNotification>(0);

	public Notification() {
	}

	public Notification(String ntName, String ntDesc, String ntText, Date createdDate, Date updatedDate,
			Set<UserNotification> userNotifications) {
		this.ntName = ntName;
		this.ntDesc = ntDesc;
		this.ntText = ntText;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.userNotifications = userNotifications;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nt_name", length = 45)
	public String getNtName() {
		return this.ntName;
	}

	public void setNtName(String ntName) {
		this.ntName = ntName;
	}

	@Column(name = "nt_desc", length = 45)
	public String getNtDesc() {
		return this.ntDesc;
	}

	public void setNtDesc(String ntDesc) {
		this.ntDesc = ntDesc;
	}

	@Column(name = "nt_text")
	public String getNtText() {
		return this.ntText;
	}

	public void setNtText(String ntText) {
		this.ntText = ntText;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notification")
	public Set<UserNotification> getUserNotifications() {
		return this.userNotifications;
	}

	public void setUserNotifications(Set<UserNotification> userNotifications) {
		this.userNotifications = userNotifications;
	}

}
