package com.zen.smi.dao.entities;
// Generated Mar 25, 2018 2:48:28 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room")
public class Room implements java.io.Serializable {

	private Integer id;
	private int roomNum;
	private String roomName;
	private int status;
	private Set<UserRoom> userRooms = new HashSet<UserRoom>(0);

	public Room() {
	}

	public Room(int roomNum, int status) {
		this.roomNum = roomNum;
		this.status = status;
	}

	public Room(int roomNum, String roomName, int status, Set<UserRoom> userRooms) {
		this.roomNum = roomNum;
		this.roomName = roomName;
		this.status = status;
		this.userRooms = userRooms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "room_num", nullable = false)
	public int getRoomNum() {
		return this.roomNum;
	}

	public void setRoomNum(int roomNum) {
		this.roomNum = roomNum;
	}

	@Column(name = "room_name", length = 45)
	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<UserRoom> getUserRooms() {
		return this.userRooms;
	}

	public void setUserRooms(Set<UserRoom> userRooms) {
		this.userRooms = userRooms;
	}

}
