package com.zen.smi.dao.entities;
// Generated Mar 25, 2018 2:48:28 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserFines generated by hbm2java
 */
@Entity
@Table(name = "user_fines", catalog = "project")
public class UserFines implements java.io.Serializable {

	private Integer userFinesId;
	private Book book;
	private Fines fines;
	private Users users;
	private String desc;
	private Date payDate;
	private int status;

	public UserFines() {
	}

	public UserFines(Users users, int status) {
		this.users = users;
		this.status = status;
	}

	public UserFines(Book book, Fines fines, Users users, String desc, Date payDate, int status) {
		this.book = book;
		this.fines = fines;
		this.users = users;
		this.desc = desc;
		this.payDate = payDate;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_fines_id", unique = true, nullable = false)
	public Integer getUserFinesId() {
		return this.userFinesId;
	}

	public void setUserFinesId(Integer userFinesId) {
		this.userFinesId = userFinesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_id")
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fine_id")
	public Fines getFines() {
		return this.fines;
	}

	public void setFines(Fines fines) {
		this.fines = fines;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "desc", length = 45)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pay_date", length = 19)
	public Date getPayDate() {
		return this.payDate;
	}

	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
