package com.zen.smi.dao.entities;
// Generated Mar 25, 2018 2:48:28 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsersBooks generated by hbm2java
 */
@Entity
@Table(name = "users_books", catalog = "project")
public class UsersBooks implements java.io.Serializable {

	private Integer usersBooksId;
	private Book book;
	private Users users;
	private int bookStatus;
	private Date bookedDate;
	private Date expiryDate;

	public UsersBooks() {
	}

	public UsersBooks(Book book, Users users, int bookStatus) {
		this.book = book;
		this.users = users;
		this.bookStatus = bookStatus;
	}

	public UsersBooks(Book book, Users users, int bookStatus, Date bookedDate, Date expiryDate) {
		this.book = book;
		this.users = users;
		this.bookStatus = bookStatus;
		this.bookedDate = bookedDate;
		this.expiryDate = expiryDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "users_books_id", unique = true, nullable = false)
	public Integer getUsersBooksId() {
		return this.usersBooksId;
	}

	public void setUsersBooksId(Integer usersBooksId) {
		this.usersBooksId = usersBooksId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_id", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "book_status", nullable = false)
	public int getBookStatus() {
		return this.bookStatus;
	}

	public void setBookStatus(int bookStatus) {
		this.bookStatus = bookStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "booked_date", length = 19)
	public Date getBookedDate() {
		return this.bookedDate;
	}

	public void setBookedDate(Date bookedDate) {
		this.bookedDate = bookedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_date", length = 19)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

}
