package com.zen.smi.dao.entities;
// Generated Mar 25, 2018 2:48:28 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRoom generated by hbm2java
 */
@Entity
@Table(name = "user_room")
public class UserRoom implements java.io.Serializable {

	private Integer userRoomId;
	private Room room;
	private Users users;
	private Date reserveTime;
	private Date leaveTime;

	public UserRoom() {
	}

	public UserRoom(Room room, Users users, Date reserveTime, Date leaveTime) {
		this.room = room;
		this.users = users;
		this.reserveTime = reserveTime;
		this.leaveTime = leaveTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_room_id", unique = true, nullable = false)
	public Integer getUserRoomId() {
		return this.userRoomId;
	}

	public void setUserRoomId(Integer userRoomId) {
		this.userRoomId = userRoomId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id", nullable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reserve_time", nullable = false, length = 19)
	public Date getReserveTime() {
		return this.reserveTime;
	}

	public void setReserveTime(Date reserveTime) {
		this.reserveTime = reserveTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "leave_time", nullable = false, length = 19)
	public Date getLeaveTime() {
		return this.leaveTime;
	}

	public void setLeaveTime(Date leaveTime) {
		this.leaveTime = leaveTime;
	}

}
